config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "articles#index"
  resources :articles
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def index
    @articles = Article.all
  end

  def show
    @article = Article.find(params[:id])
  end

  def new
    @article = Article.new
  end

  def create
    article = Article.new(article_params)
    article.save
    redirect_to articles_path
  end

  def edit
    @article = Article.find(params[:id])
  end

  def update
    @article = Article.find(params[:id])
    @article.update(article_params)
    redirect_to article_path(@article)
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy
    redirect_to articles_path
  end

  private

  def article_params
    params.require(:article).permit(:title, :content)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/edit.html.erb
<h1>Edit article</h1>

<%= simple_form_for(@article) do |f| %>
  <%= f.input :title, hint: "Not too long plz" %>
  <%= f.input :content, size: "150" %>
  <%= f.submit :class => "btn btn-success" %>
<% end %>

<hr>

<%= link_to "← Back to the list", articles_path %>

app/views/articles/index.html.erb
<h1>All my articles</h1>

<% @articles.each do |article| %>
  <article>
    <h3><%= link_to article.title, article_path(article) %></h3>
    <% article_beginning = article.content.first(100) %>
    <p><%= article_beginning %>...</p>
  </article>
<% end %>

app/views/articles/new.html.erb
<h1>New article</h1>

<%= simple_form_for(@article) do |f| %>
  <%= f.input :title %>
  <%= f.input :content %>
  <%= f.submit :class => "btn btn-success" %>
<% end %>

<hr>

<%= link_to "← Back to the list", articles_path %>

app/views/articles/show.html.erb
<h1 class="mt-4 show-title">
  <%= @article.title %>
  <%= link_to "✎", edit_article_path %>
  <%= link_to "🗑", article_path(@article), method: :delete, data: { confirm: "Are you sure?" } %>
</h1>

<hr>

<p><%= @article.content %></p>

<hr>

<%= link_to "← Back to the list", articles_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWikinimous</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-light bg-light">
      <%= link_to "Wikifabinimous", articles_path, :class => "navbar-brand" %>
      <%= link_to "New Article", new_article_path %>
    </nav>

    <div class="container">
      <div class="row d-flex flex-column">
        <div class="col-8 w-100 justify-content-center">
          <%= yield %>
        </div>
      </div>
    </div>
  </body>
</html>